apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.tcpSync }}
      targetPort: tcp-sync
      protocol: TCP
      name: tcp-sync
    - port: {{ .Values.service.port.quicSync }}
      targetPort: quic-sync
      protocol: UDP
      name: quic-sync
    - port: {{ .Values.service.port.discovery }}
      targetPort: discovery
      protocol: UDP
      name: discovery
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
