apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adguard.fullname" . }}
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
data:
  {{- include "common.tplvalues.render" (dict "value" .Values.configMap "context" $) | nindent 2 }}
