apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adguard.fullname" . }}
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
data:
  AdGuardHome.yaml: |
    {{- include "common.tplvalues.render" (dict "value" .Values.config "context" $) | nindent 4 }}
